// Software: MISO iOS
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Pierre-Yves Lapersonne

import Foundation
import MISOTokensRaw
import MISOTokensSemantic

// swiftlint:disable file_length

extension BlueCoatThemeColorSemanticTokensProvider: ColorSemanticTokens {
    /// Has for value token repositoryOpacityWhiteMediumLow (= "#EFF5FF33")
    @objc open var actionDisabledDark: ColorSemanticToken { repositoryOpacityWhiteMediumLow }
    /// Has for value token repositoryOpacityBlackMediumLow (= "#05052E33")
    @objc open var actionDisabledLight: ColorSemanticToken { repositoryOpacityBlackMediumLow }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var actionEnabledDark: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var actionEnabledLight: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositoryPrimaryLower (= "#C1D8FCFF")
    @objc open var actionFocusDark: ColorSemanticToken { repositoryPrimaryLower }
    /// Has for value token repositoryPrimaryHigh (= "#223CABFF")
    @objc open var actionFocusLight: ColorSemanticToken { repositoryPrimaryHigh }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var actionHighlightedDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryPrimaryHigh (= "#223CABFF")
    @objc open var actionHighlightedLight: ColorSemanticToken { repositoryPrimaryHigh }
    /// Has for value token repositoryPrimaryLower (= "#C1D8FCFF")
    @objc open var actionHoverDark: ColorSemanticToken { repositoryPrimaryLower }
    /// Has for value token repositoryPrimaryHigh (= "#223CABFF")
    @objc open var actionHoverLight: ColorSemanticToken { repositoryPrimaryHigh }
    /// Has for value token repositoryPrimaryLowest (= "#DCE9FDFF")
    @objc open var actionLoadingDark: ColorSemanticToken { repositoryPrimaryLowest }
    /// Has for value token repositoryPrimaryHigher (= "#213787FF")
    @objc open var actionLoadingLight: ColorSemanticToken { repositoryPrimaryHigher }
    /// Has for value token repositoryNegativeLow (= "#FF8081FF")
    @objc open var actionNegativeEnabledDark: ColorSemanticToken { repositoryNegativeLow }
    /// Has for value token repositoryNegativeMedium (= "#DB0002FF")
    @objc open var actionNegativeEnabledLight: ColorSemanticToken { repositoryNegativeMedium }
    /// Has for value token repositoryNegativeLower (= "#FFB2B3FF")
    @objc open var actionNegativeFocusDark: ColorSemanticToken { repositoryNegativeLower }
    /// Has for value token repositoryNegativeHigh (= "#B20002FF")
    @objc open var actionNegativeFocusLight: ColorSemanticToken { repositoryNegativeHigh }
    /// Has for value token repositoryNegativeLower (= "#FFB2B3FF")
    @objc open var actionNegativeHoverDark: ColorSemanticToken { repositoryNegativeLower }
    /// Has for value token repositoryNegativeHigh (= "#B20002FF")
    @objc open var actionNegativeHoverLight: ColorSemanticToken { repositoryNegativeHigh }
    /// Has for value token repositoryNegativeLowest (= "#FFE5E6FF")
    @objc open var actionNegativeLoadingDark: ColorSemanticToken { repositoryNegativeLowest }
    /// Has for value token repositoryNegativeHigher (= "#800001FF")
    @objc open var actionNegativeLoadingLight: ColorSemanticToken { repositoryNegativeHigher }
    /// Has for value token repositoryNegativeLowest (= "#FFE5E6FF")
    @objc open var actionNegativePressedDark: ColorSemanticToken { repositoryNegativeLowest }
    /// Has for value token repositoryNegativeHigher (= "#800001FF")
    @objc open var actionNegativePressedLight: ColorSemanticToken { repositoryNegativeHigher }
    /// Has for value token repositoryPrimaryLowest (= "#DCE9FDFF")
    @objc open var actionPressedDark: ColorSemanticToken { repositoryPrimaryLowest }
    /// Has for value token repositoryPrimaryHigher (= "#213787FF")
    @objc open var actionPressedLight: ColorSemanticToken { repositoryPrimaryHigher }
    /// Has for value token repositoryPrimaryLower (= "#C1D8FCFF")
    @objc open var actionReadOnlyPrimaryDark: ColorSemanticToken { repositoryPrimaryLower }
    /// Has for value token repositoryPrimaryHigh (= "#223CABFF")
    @objc open var actionReadOnlyPrimaryLight: ColorSemanticToken { repositoryPrimaryHigh }
    /// Has for value token repositoryOpacityWhiteMediumLow (= "#EFF5FF33")
    @objc open var actionReadOnlySecondaryDark: ColorSemanticToken { repositoryOpacityWhiteMediumLow }
    /// Has for value token repositoryOpacityBlackMediumLow (= "#05052E33")
    @objc open var actionReadOnlySecondaryLight: ColorSemanticToken { repositoryOpacityBlackMediumLow }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var actionSelectedDark: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var actionSelectedLight: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositoryOpacityWhiteLowest (= "#EFF5FF0A")
    @objc open var actionSupportDisabledDark: ColorSemanticToken { repositoryOpacityWhiteLowest }
    /// Has for value token repositoryOpacityBlackLowest (= "#05052E0A")
    @objc open var actionSupportDisabledLight: ColorSemanticToken { repositoryOpacityBlackLowest }
    /// Has for value token repositoryOpacityWhiteLowest (= "#EFF5FF0A")
    @objc open var actionSupportEnabledDark: ColorSemanticToken { repositoryOpacityWhiteLowest }
    /// Has for value token repositoryOpacityBlackLowest (= "#05052E0A")
    @objc open var actionSupportEnabledLight: ColorSemanticToken { repositoryOpacityBlackLowest }
    /// Has for value token repositoryOpacityWhiteLower (= "#EFF5FF14")
    @objc open var actionSupportFocusDark: ColorSemanticToken { repositoryOpacityWhiteLower }
    /// Has for value token repositoryOpacityBlackLower (= "#05052E14")
    @objc open var actionSupportFocusLight: ColorSemanticToken { repositoryOpacityBlackLower }
    /// Has for value token repositoryOpacityWhiteLower (= "#EFF5FF14")
    @objc open var actionSupportHoverDark: ColorSemanticToken { repositoryOpacityWhiteLower }
    /// Has for value token repositoryOpacityBlackLower (= "#05052E14")
    @objc open var actionSupportHoverLight: ColorSemanticToken { repositoryOpacityBlackLower }
    /// Has for value token repositoryOpacityWhiteLow (= "#EFF5FF1F")
    @objc open var actionSupportLoadingDark: ColorSemanticToken { repositoryOpacityWhiteLow }
    /// Has for value token repositoryOpacityBlackLow (= "#05052E1F")
    @objc open var actionSupportLoadingLight: ColorSemanticToken { repositoryOpacityBlackLow }
    /// Has for value token repositoryOpacityWhiteLow (= "#EFF5FF1F")
    @objc open var actionSupportPressedDark: ColorSemanticToken { repositoryOpacityWhiteLow }
    /// Has for value token repositoryOpacityBlackLow (= "#05052E1F")
    @objc open var actionSupportPressedLight: ColorSemanticToken { repositoryOpacityBlackLow }
    /// Has for value token ColorRawTokens.functionalAmethyst400 (= "#A885D8FF")
    @objc open var actionVisitedDark: ColorSemanticToken { ColorRawTokens.functionalAmethyst400 }
    /// Has for value token ColorRawTokens.functionalAmethyst600 (= "#5B2F98FF")
    @objc open var actionVisitedLight: ColorSemanticToken { ColorRawTokens.functionalAmethyst600 }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var colorAiPrimaryDark: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var colorAiPrimaryLight: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var colorAiQuaternaryDark: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var colorAiQuaternaryLight: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var colorAiSecondaryDark: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var colorAiSecondaryLight: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var colorAiTertiaryDark: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var colorAiTertiaryLight: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var alwaysBlack: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var alwaysOnBlack: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var alwaysOnWhite: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var alwaysWhite: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var bgInverseHighDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedHigher (= "#181C26FF")
    @objc open var bgInverseHighLight: ColorSemanticToken { repositoryNeutralEmphasizedHigher }
    /// Has for value token repositoryNeutralEmphasizedHigh (= "#1F2632FF")
    @objc open var bgInverseLowDark: ColorSemanticToken { repositoryNeutralEmphasizedHigh }
    /// Has for value token repositoryNeutralEmphasizedHigher (= "#181C26FF")
    @objc open var bgInverseLowLight: ColorSemanticToken { repositoryNeutralEmphasizedHigher }
    /// Has for value token repositoryNeutralEmphasizedHighest (= "#101319FF")
    @objc open var bgPrimaryDark: ColorSemanticToken { repositoryNeutralEmphasizedHighest }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var bgPrimaryLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedHigher (= "#181C26FF")
    @objc open var bgSecondaryDark: ColorSemanticToken { repositoryNeutralEmphasizedHigher }
    /// Has for value token repositoryNeutralMutedLowest (= "#F7F8FAFF")
    @objc open var bgSecondaryLight: ColorSemanticToken { repositoryNeutralMutedLowest }
    /// Has for value token repositoryAccentHighest (= "#380513FF")
    @objc open var bgTertiaryDark: ColorSemanticToken { repositoryAccentHighest }
    /// Has for value token repositoryAccentLowest (= "#FFF1F1FF")
    @objc open var bgTertiaryLight: ColorSemanticToken { repositoryAccentLowest }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var borderBrandPrimaryDark: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var borderBrandPrimaryLight: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositorySecondaryLow (= "#F66F7DFF")
    @objc open var borderBrandSecondaryDark: ColorSemanticToken { repositorySecondaryLow }
    /// Has for value token repositorySecondaryMedium (= "#DB2345FF")
    @objc open var borderBrandSecondaryLight: ColorSemanticToken { repositorySecondaryMedium }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var borderBrandTertiaryDark: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var borderBrandTertiaryLight: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token repositoryOpacityWhiteMediumLow (= "#EFF5FF33")
    @objc open var borderDefaultDark: ColorSemanticToken { repositoryOpacityWhiteMediumLow }
    /// Has for value token repositoryOpacityBlackMediumLow (= "#05052E33")
    @objc open var borderDefaultLight: ColorSemanticToken { repositoryOpacityBlackMediumLow }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var borderEmphasizedDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var borderEmphasizedLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryPrimaryLowest (= "#DCE9FDFF")
    @objc open var borderFocusDark: ColorSemanticToken { repositoryPrimaryLowest }
    /// Has for value token repositoryNeutralEmphasizedHighest (= "#101319FF")
    @objc open var borderFocusInsetDark: ColorSemanticToken { repositoryNeutralEmphasizedHighest }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var borderFocusInsetLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryPrimaryHigher (= "#213787FF")
    @objc open var borderFocusLight: ColorSemanticToken { repositoryPrimaryHigher }
    /// Has for value token repositoryOpacityWhiteLowest (= "#EFF5FF0A")
    @objc open var borderMinimalDark: ColorSemanticToken { repositoryOpacityWhiteLowest }
    /// Has for value token repositoryOpacityBlackLowest (= "#05052E0A")
    @objc open var borderMinimalLight: ColorSemanticToken { repositoryOpacityBlackLowest }
    /// Has for value token repositoryOpacityWhiteLow (= "#EFF5FF1F")
    @objc open var borderMutedDark: ColorSemanticToken { repositoryOpacityWhiteLow }
    /// Has for value token repositoryOpacityBlackLow (= "#05052E1F")
    @objc open var borderMutedLight: ColorSemanticToken { repositoryOpacityBlackLow }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var borderOnBrandPrimaryDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var borderOnBrandPrimaryLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var borderOnBrandSecondaryDark: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var borderOnBrandSecondaryLight: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var borderOnBrandTertiaryDark: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var borderOnBrandTertiaryLight: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token repositoryAccentLow (= "#FA9EA6FF")
    @objc open var borderStatusAccentDark: ColorSemanticToken { repositoryAccentLow }
    /// Has for value token repositoryAccentMedium (= "#DB2345FF")
    @objc open var borderStatusAccentLight: ColorSemanticToken { repositoryAccentMedium }
    /// Has for value token repositoryInfoLow (= "#8AD5FFFF")
    @objc open var borderStatusInfoDark: ColorSemanticToken { repositoryInfoLow }
    /// Has for value token repositoryInfoHigh (= "#0073B2FF")
    @objc open var borderStatusInfoLight: ColorSemanticToken { repositoryInfoHigh }
    /// Has for value token repositoryNegativeLow (= "#FF8081FF")
    @objc open var borderStatusNegativeDark: ColorSemanticToken { repositoryNegativeLow }
    /// Has for value token repositoryNegativeMedium (= "#DB0002FF")
    @objc open var borderStatusNegativeLight: ColorSemanticToken { repositoryNegativeMedium }
    /// Has for value token repositoryPositiveLow (= "#94F0A4FF")
    @objc open var borderStatusPositiveDark: ColorSemanticToken { repositoryPositiveLow }
    /// Has for value token repositoryPositiveHigher (= "#138126FF")
    @objc open var borderStatusPositiveLight: ColorSemanticToken { repositoryPositiveHigher }
    /// Has for value token repositoryWarningLow (= "#FFE270FF")
    @objc open var borderStatusWarningDark: ColorSemanticToken { repositoryWarningLow }
    /// Has for value token repositoryWarningMedium (= "#FFD000FF")
    @objc open var borderStatusWarningLight: ColorSemanticToken { repositoryWarningMedium }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var contentBrandPrimaryDark: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var contentBrandPrimaryLight: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositorySecondaryLow (= "#F66F7DFF")
    @objc open var contentBrandSecondaryDark: ColorSemanticToken { repositorySecondaryLow }
    /// Has for value token repositorySecondaryMedium (= "#DB2345FF")
    @objc open var contentBrandSecondaryLight: ColorSemanticToken { repositorySecondaryMedium }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var contentBrandTertiaryDark: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var contentBrandTertiaryLight: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var contentDefaultDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentDefaultLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryOpacityWhiteMediumLow (= "#EFF5FF33")
    @objc open var contentDisabledDark: ColorSemanticToken { repositoryOpacityWhiteMediumLow }
    /// Has for value token repositoryOpacityBlackMediumLow (= "#05052E33")
    @objc open var contentDisabledLight: ColorSemanticToken { repositoryOpacityBlackMediumLow }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentInverseDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentInverseLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryOpacityWhiteHigh (= "#EFF5FFA3")
    @objc open var contentMutedDark: ColorSemanticToken { repositoryOpacityWhiteHigh }
    /// Has for value token repositoryOpacityBlackHigher (= "#05052EAD")
    @objc open var contentMutedLight: ColorSemanticToken { repositoryOpacityBlackHigher }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionDisabledDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionDisabledLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionEnabledDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionEnabledLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionFocusDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionFocusLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionHighlightedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionHighlightedLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionHoverDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionHoverLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionLoadingDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionLoadingLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionPressedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionPressedLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnActionSelectedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnActionSelectedLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnBrandPrimaryDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnBrandPrimaryLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnBrandSecondaryDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnBrandSecondaryLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var contentOnBrandTertiaryDark: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var contentOnBrandTertiaryLight: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusAccentEmphasizedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnStatusAccentEmphasizedLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var contentOnStatusAccentMutedDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusAccentMutedLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusInfoEmphasizedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnStatusInfoEmphasizedLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var contentOnStatusInfoMutedDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusInfoMutedLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusNegativeEmphasizedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnStatusNegativeEmphasizedLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var contentOnStatusNegativeMutedDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusNegativeMutedLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusPositiveEmphasizedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var contentOnStatusPositiveEmphasizedLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var contentOnStatusPositiveMutedDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusPositiveMutedLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusWarningEmphasizedDark: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusWarningEmphasizedLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var contentOnStatusWarningMutedDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedBlack (= "#08090DFF")
    @objc open var contentOnStatusWarningMutedLight: ColorSemanticToken { repositoryNeutralEmphasizedBlack }
    /// Has for value token repositoryAccentLow (= "#FA9EA6FF")
    @objc open var contentStatusAccentDark: ColorSemanticToken { repositoryAccentLow }
    /// Has for value token repositoryAccentMedium (= "#DB2345FF")
    @objc open var contentStatusAccentLight: ColorSemanticToken { repositoryAccentMedium }
    /// Has for value token repositoryInfoLow (= "#8AD5FFFF")
    @objc open var contentStatusInfoDark: ColorSemanticToken { repositoryInfoLow }
    /// Has for value token repositoryInfoHigh (= "#0073B2FF")
    @objc open var contentStatusInfoLight: ColorSemanticToken { repositoryInfoHigh }
    /// Has for value token repositoryInfoHigh (= "#0073B2FF")
    @objc open var contentStatusInverseInfoDark: ColorSemanticToken { repositoryInfoHigh }
    /// Has for value token repositoryInfoLow (= "#8AD5FFFF")
    @objc open var contentStatusInverseInfoLight: ColorSemanticToken { repositoryInfoLow }
    /// Has for value token repositoryNegativeMedium (= "#DB0002FF")
    @objc open var contentStatusInverseNegativeDark: ColorSemanticToken { repositoryNegativeMedium }
    /// Has for value token repositoryNegativeLow (= "#FF8081FF")
    @objc open var contentStatusInverseNegativeLight: ColorSemanticToken { repositoryNegativeLow }
    /// Has for value token repositoryPositiveHigher (= "#138126FF")
    @objc open var contentStatusInversePositiveDark: ColorSemanticToken { repositoryPositiveHigher }
    /// Has for value token repositoryPositiveLow (= "#94F0A4FF")
    @objc open var contentStatusInversePositiveLight: ColorSemanticToken { repositoryPositiveLow }
    /// Has for value token repositoryWarningHigh (= "#856A00FF")
    @objc open var contentStatusInverseWarningDark: ColorSemanticToken { repositoryWarningHigh }
    /// Has for value token repositoryWarningLow (= "#FFE270FF")
    @objc open var contentStatusInverseWarningLight: ColorSemanticToken { repositoryWarningLow }
    /// Has for value token repositoryNegativeLow (= "#FF8081FF")
    @objc open var contentStatusNegativeDark: ColorSemanticToken { repositoryNegativeLow }
    /// Has for value token repositoryNegativeMedium (= "#DB0002FF")
    @objc open var contentStatusNegativeLight: ColorSemanticToken { repositoryNegativeMedium }
    /// Has for value token repositoryPositiveLow (= "#94F0A4FF")
    @objc open var contentStatusPositiveDark: ColorSemanticToken { repositoryPositiveLow }
    /// Has for value token repositoryPositiveHigher (= "#138126FF")
    @objc open var contentStatusPositiveLight: ColorSemanticToken { repositoryPositiveHigher }
    /// Has for value token repositoryWarningLow (= "#FFE270FF")
    @objc open var contentStatusWarningDark: ColorSemanticToken { repositoryWarningLow }
    /// Has for value token repositoryWarningHigh (= "#856A00FF")
    @objc open var contentStatusWarningLight: ColorSemanticToken { repositoryWarningHigh }
    /// Has for value token repositoryOpacityWhiteLower (= "#EFF5FF14")
    @objc open var opacityLowerDark: ColorSemanticToken { repositoryOpacityWhiteLower }
    /// Has for value token repositoryOpacityBlackLower (= "#05052E14")
    @objc open var opacityLowerLight: ColorSemanticToken { repositoryOpacityBlackLower }
    /// Has for value token repositoryOpacityWhiteLowest (= "#EFF5FF0A")
    @objc open var opacityLowestDark: ColorSemanticToken { repositoryOpacityWhiteLowest }
    /// Has for value token repositoryOpacityBlackLowest (= "#05052E0A")
    @objc open var opacityLowestLight: ColorSemanticToken { repositoryOpacityBlackLowest }
    /// Has for value token repositoryOpacityWhiteTransparent (= "#EFF5FF00")
    @objc open var opacityTransparentDark: ColorSemanticToken { repositoryOpacityWhiteTransparent }
    /// Has for value token repositoryOpacityBlackTransparent (= "#05052E00")
    @objc open var opacityTransparentInverseDark: ColorSemanticToken { repositoryOpacityBlackTransparent }
    /// Has for value token repositoryOpacityWhiteTransparent (= "#EFF5FF00")
    @objc open var opacityTransparentInverseLight: ColorSemanticToken { repositoryOpacityWhiteTransparent }
    /// Has for value token repositoryOpacityBlackTransparent (= "#05052E00")
    @objc open var opacityTransparentLight: ColorSemanticToken { repositoryOpacityBlackTransparent }
    /// Has for value token repositoryOpacityBlackHigher (= "#05052EAD")
    @objc open var overlayBackdropDark: ColorSemanticToken { repositoryOpacityBlackHigher }
    /// Has for value token repositoryOpacityBlackHigher (= "#05052EAD")
    @objc open var overlayBackdropLight: ColorSemanticToken { repositoryOpacityBlackHigher }
    /// Has for value token repositoryOpacityWhiteLower (= "#EFF5FF14")
    @objc open var overlayDragDark: ColorSemanticToken { repositoryOpacityWhiteLower }
    /// Has for value token repositoryOpacityBlackLowest (= "#05052E0A")
    @objc open var overlayDragLight: ColorSemanticToken { repositoryOpacityBlackLowest }
    /// Has for value token repositoryNeutralEmphasizedLow (= "#2F384BFF")
    @objc open var overlayDropdownDark: ColorSemanticToken { repositoryNeutralEmphasizedLow }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var overlayDropdownLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedLow (= "#2F384BFF")
    @objc open var overlayFloatingDark: ColorSemanticToken { repositoryNeutralEmphasizedLow }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var overlayFloatingLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedHigh (= "#1F2632FF")
    @objc open var overlayModalSheetDark: ColorSemanticToken { repositoryNeutralEmphasizedHigh }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var overlayModalSheetLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryNeutralEmphasizedLow (= "#2F384BFF")
    @objc open var overlayTooltipDark: ColorSemanticToken { repositoryNeutralEmphasizedLow }
    /// Has for value token repositoryNeutralEmphasizedHigh (= "#1F2632FF")
    @objc open var overlayTooltipLight: ColorSemanticToken { repositoryNeutralEmphasizedHigh }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryAccentHigh: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed900 (= "#681229FF")
    @objc open var repositoryAccentHigher: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed900 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed1000 (= "#380513FF")
    @objc open var repositoryAccentHighest: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed1000 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed300 (= "#FA9EA6FF")
    @objc open var repositoryAccentLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed300 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryAccentLower: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed50 (= "#FFF1F1FF")
    @objc open var repositoryAccentLowest: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed50 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed600 (= "#DB2345FF")
    @objc open var repositoryAccentMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed600 }
    /// Has for value token ColorRawTokens.functionalDodgerBlue700 (= "#0073B2FF")
    @objc open var repositoryInfoHigh: ColorSemanticToken { ColorRawTokens.functionalDodgerBlue700 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryInfoHigher: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryInfoHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalDodgerBlue300 (= "#8AD5FFFF")
    @objc open var repositoryInfoLow: ColorSemanticToken { ColorRawTokens.functionalDodgerBlue300 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryInfoLower: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryInfoLowest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryInfoMedium: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalScarlet700 (= "#B20002FF")
    @objc open var repositoryNegativeHigh: ColorSemanticToken { ColorRawTokens.functionalScarlet700 }
    /// Has for value token ColorRawTokens.functionalScarlet800 (= "#800001FF")
    @objc open var repositoryNegativeHigher: ColorSemanticToken { ColorRawTokens.functionalScarlet800 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNegativeHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalScarlet300 (= "#FF8081FF")
    @objc open var repositoryNegativeLow: ColorSemanticToken { ColorRawTokens.functionalScarlet300 }
    /// Has for value token ColorRawTokens.functionalScarlet200 (= "#FFB2B3FF")
    @objc open var repositoryNegativeLower: ColorSemanticToken { ColorRawTokens.functionalScarlet200 }
    /// Has for value token ColorRawTokens.functionalScarlet100 (= "#FFE5E6FF")
    @objc open var repositoryNegativeLowest: ColorSemanticToken { ColorRawTokens.functionalScarlet100 }
    /// Has for value token ColorRawTokens.functionalScarlet600 (= "#DB0002FF")
    @objc open var repositoryNegativeMedium: ColorSemanticToken { ColorRawTokens.functionalScarlet600 }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayDark960 (= "#08090DFF")
    @objc open var repositoryNeutralEmphasizedBlack: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayDark960 }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayDark720 (= "#1F2632FF")
    @objc open var repositoryNeutralEmphasizedHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayDark720 }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayDark800 (= "#181C26FF")
    @objc open var repositoryNeutralEmphasizedHigher: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayDark800 }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayDark880 (= "#101319FF")
    @objc open var repositoryNeutralEmphasizedHighest: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayDark880 }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayDark560 (= "#2F384BFF")
    @objc open var repositoryNeutralEmphasizedLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayDark560 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNeutralEmphasizedLower: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNeutralEmphasizedLowest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayDark640 (= "#272F3FFF")
    @objc open var repositoryNeutralEmphasizedMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayDark640 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNeutralMutedHigh: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNeutralMutedHigher: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNeutralMutedHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNeutralMutedLow: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayLight160 (= "#E9ECF1FF")
    @objc open var repositoryNeutralMutedLower: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayLight160 }
    /// Has for value token BlueCoatBrandColorRawTokens.functionalGrayLight80 (= "#F7F8FAFF")
    @objc open var repositoryNeutralMutedLowest: ColorSemanticToken { BlueCoatBrandColorRawTokens.functionalGrayLight80 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryNeutralMutedMedium: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalWhite (= "#FFFFFFFF")
    @objc open var repositoryNeutralMutedWhite: ColorSemanticToken { ColorRawTokens.functionalWhite }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRustyRed80 (= "#DB234514")
    @objc open var repositoryOpacityAccentLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRustyRed80 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRustyRed680 (= "#8E1532AD")
    @objc open var repositoryOpacityAccentMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRustyRed680 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack520 (= "#05052E85")
    @objc open var repositoryOpacityBlackHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack520 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack680 (= "#05052EAD")
    @objc open var repositoryOpacityBlackHigher: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack680 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack920 (= "#05052EEB")
    @objc open var repositoryOpacityBlackHighest: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack920 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack120 (= "#05052E1F")
    @objc open var repositoryOpacityBlackLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack120 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack80 (= "#05052E14")
    @objc open var repositoryOpacityBlackLower: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack80 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack40 (= "#05052E0A")
    @objc open var repositoryOpacityBlackLowest: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack40 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack280 (= "#05052E47")
    @objc open var repositoryOpacityBlackMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack280 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack440 (= "#05052E70")
    @objc open var repositoryOpacityBlackMediumHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack440 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack200 (= "#05052E33")
    @objc open var repositoryOpacityBlackMediumLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack200 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityBlack0 (= "#05052E00")
    @objc open var repositoryOpacityBlackTransparent: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityBlack0 }
    /// Has for value token ColorRawTokens.dodgerBlue80 (= "#26B2FF14")
    @objc open var repositoryOpacityInfoLow: ColorSemanticToken { ColorRawTokens.dodgerBlue80 }
    /// Has for value token ColorRawTokens.dodgerBlue520 (= "#00598A85")
    @objc open var repositoryOpacityInfoMedium: ColorSemanticToken { ColorRawTokens.dodgerBlue520 }
    /// Has for value token ColorRawTokens.scarlet80 (= "#DB000214")
    @objc open var repositoryOpacityNegativeLow: ColorSemanticToken { ColorRawTokens.scarlet80 }
    /// Has for value token ColorRawTokens.scarlet320 (= "#DB000252")
    @objc open var repositoryOpacityNegativeMedium: ColorSemanticToken { ColorRawTokens.scarlet320 }
    /// Has for value token ColorRawTokens.malachite120 (= "#3DE35A1F")
    @objc open var repositoryOpacityPositiveLow: ColorSemanticToken { ColorRawTokens.malachite120 }
    /// Has for value token ColorRawTokens.malachite640 (= "#0E621DA3")
    @objc open var repositoryOpacityPositiveMedium: ColorSemanticToken { ColorRawTokens.malachite640 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRoyalBlue560 (= "#2055E58F")
    @objc open var repositoryOpacityPrimaryHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRoyalBlue560 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRoyalBlue680 (= "#2055E5AD")
    @objc open var repositoryOpacityPrimaryHigher: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRoyalBlue680 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryOpacityPrimaryHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRoyalBlue360 (= "#2055E55C")
    @objc open var repositoryOpacityPrimaryLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRoyalBlue360 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRoyalBlue200 (= "#2055E533")
    @objc open var repositoryOpacityPrimaryLower: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRoyalBlue200 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRoyalBlue80 (= "#2055E514")
    @objc open var repositoryOpacityPrimaryLowest: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRoyalBlue80 }
    /// Has for value token BlueCoatBrandColorRawTokens.opacityRoyalBlue400 (= "#2055E566")
    @objc open var repositoryOpacityPrimaryMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.opacityRoyalBlue400 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryOpacityPrimaryTransparent: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.sun160 (= "#FFD00029")
    @objc open var repositoryOpacityWarningLow: ColorSemanticToken { ColorRawTokens.sun160 }
    /// Has for value token ColorRawTokens.sun480 (= "#6651007A")
    @objc open var repositoryOpacityWarningMedium: ColorSemanticToken { ColorRawTokens.sun480 }
    /// Has for value token BlueCoatBrandColorRawTokens.white640 (= "#EFF5FFA3")
    @objc open var repositoryOpacityWhiteHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.white640 }
    /// Has for value token BlueCoatBrandColorRawTokens.white800 (= "#EFF5FFCC")
    @objc open var repositoryOpacityWhiteHigher: ColorSemanticToken { BlueCoatBrandColorRawTokens.white800 }
    /// Has for value token BlueCoatBrandColorRawTokens.white920 (= "#EFF5FFEB")
    @objc open var repositoryOpacityWhiteHighest: ColorSemanticToken { BlueCoatBrandColorRawTokens.white920 }
    /// Has for value token BlueCoatBrandColorRawTokens.white120 (= "#EFF5FF1F")
    @objc open var repositoryOpacityWhiteLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.white120 }
    /// Has for value token BlueCoatBrandColorRawTokens.white80 (= "#EFF5FF14")
    @objc open var repositoryOpacityWhiteLower: ColorSemanticToken { BlueCoatBrandColorRawTokens.white80 }
    /// Has for value token BlueCoatBrandColorRawTokens.white40 (= "#EFF5FF0A")
    @objc open var repositoryOpacityWhiteLowest: ColorSemanticToken { BlueCoatBrandColorRawTokens.white40 }
    /// Has for value token BlueCoatBrandColorRawTokens.white440 (= "#EFF5FF70")
    @objc open var repositoryOpacityWhiteMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.white440 }
    /// Has for value token BlueCoatBrandColorRawTokens.white200 (= "#EFF5FF33")
    @objc open var repositoryOpacityWhiteMediumLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.white200 }
    /// Has for value token BlueCoatBrandColorRawTokens.white0 (= "#EFF5FF00")
    @objc open var repositoryOpacityWhiteTransparent: ColorSemanticToken { BlueCoatBrandColorRawTokens.white0 }
    /// Has for value token ColorRawTokens.functionalMalachite700 (= "#17A02FFF")
    @objc open var repositoryPositiveHigh: ColorSemanticToken { ColorRawTokens.functionalMalachite700 }
    /// Has for value token ColorRawTokens.functionalMalachite750 (= "#138126FF")
    @objc open var repositoryPositiveHigher: ColorSemanticToken { ColorRawTokens.functionalMalachite750 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryPositiveHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalMalachite300 (= "#94F0A4FF")
    @objc open var repositoryPositiveLow: ColorSemanticToken { ColorRawTokens.functionalMalachite300 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryPositiveLower: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryPositiveLowest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalMalachite600 (= "#1ECD3CFF")
    @objc open var repositoryPositiveMedium: ColorSemanticToken { ColorRawTokens.functionalMalachite600 }
    /// Has for value token BlueCoatBrandColorRawTokens.royalBlue800 (= "#223CABFF")
    @objc open var repositoryPrimaryHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.royalBlue800 }
    /// Has for value token BlueCoatBrandColorRawTokens.royalBlue900 (= "#213787FF")
    @objc open var repositoryPrimaryHigher: ColorSemanticToken { BlueCoatBrandColorRawTokens.royalBlue900 }
    /// Has for value token BlueCoatBrandColorRawTokens.royalBlue950 (= "#1F2D6BFF")
    @objc open var repositoryPrimaryHighest: ColorSemanticToken { BlueCoatBrandColorRawTokens.royalBlue950 }
    /// Has for value token BlueCoatBrandColorRawTokens.royalBlue300 (= "#96C1FAFF")
    @objc open var repositoryPrimaryLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.royalBlue300 }
    /// Has for value token BlueCoatBrandColorRawTokens.royalBlue200 (= "#C1D8FCFF")
    @objc open var repositoryPrimaryLower: ColorSemanticToken { BlueCoatBrandColorRawTokens.royalBlue200 }
    /// Has for value token BlueCoatBrandColorRawTokens.royalBlue100 (= "#DCE9FDFF")
    @objc open var repositoryPrimaryLowest: ColorSemanticToken { BlueCoatBrandColorRawTokens.royalBlue100 }
    /// Has for value token BlueCoatBrandColorRawTokens.royalBlue600 (= "#2055E5FF")
    @objc open var repositoryPrimaryMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.royalBlue600 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed700 (= "#B81839FF")
    @objc open var repositorySecondaryHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed700 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed800 (= "#8E1532FF")
    @objc open var repositorySecondaryHigherHigh: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed800 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed800 (= "#8E1532FF")
    @objc open var repositorySecondaryHigherLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed800 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositorySecondaryHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed400 (= "#F66F7DFF")
    @objc open var repositorySecondaryLow: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed400 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed300 (= "#FA9EA6FF")
    @objc open var repositorySecondaryLower: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed300 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed200 (= "#FCCFD2FF")
    @objc open var repositorySecondaryLowest: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed200 }
    /// Has for value token BlueCoatBrandColorRawTokens.rustyRed600 (= "#DB2345FF")
    @objc open var repositorySecondaryMedium: ColorSemanticToken { BlueCoatBrandColorRawTokens.rustyRed600 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryTertiaryHigh: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryTertiaryHigher: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryTertiaryHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryTertiaryLow: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryTertiaryLower: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryTertiaryLowest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryTertiaryMedium: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalSun750 (= "#856A00FF")
    @objc open var repositoryWarningHigh: ColorSemanticToken { ColorRawTokens.functionalSun750 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryWarningHigher: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryWarningHighest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalSun300 (= "#FFE270FF")
    @objc open var repositoryWarningLow: ColorSemanticToken { ColorRawTokens.functionalSun300 }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryWarningLower: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var repositoryWarningLowest: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token ColorRawTokens.functionalSun500 (= "#FFD000FF")
    @objc open var repositoryWarningMedium: ColorSemanticToken { ColorRawTokens.functionalSun500 }
    /// Has for value token repositoryPrimaryLow (= "#96C1FAFF")
    @objc open var surfaceBrandPrimaryDark: ColorSemanticToken { repositoryPrimaryLow }
    /// Has for value token repositoryPrimaryMedium (= "#2055E5FF")
    @objc open var surfaceBrandPrimaryLight: ColorSemanticToken { repositoryPrimaryMedium }
    /// Has for value token repositorySecondaryLow (= "#F66F7DFF")
    @objc open var surfaceBrandSecondaryDark: ColorSemanticToken { repositorySecondaryLow }
    /// Has for value token repositorySecondaryMedium (= "#DB2345FF")
    @objc open var surfaceBrandSecondaryLight: ColorSemanticToken { repositorySecondaryMedium }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var surfaceBrandTertiaryDark: ColorSemanticToken { "miso-forbidden-color-value" }
    /// This token has a forbidden color value (#FF000000 in tokenator) and **must not be used if you use this BlueCoatTheme**
    @objc open var surfaceBrandTertiaryLight: ColorSemanticToken { "miso-forbidden-color-value" }
    /// Has for value token repositoryNeutralMutedLower (= "#E9ECF1FF")
    @objc open var surfaceInverseHighDark: ColorSemanticToken { repositoryNeutralMutedLower }
    /// Has for value token repositoryNeutralEmphasizedHigh (= "#1F2632FF")
    @objc open var surfaceInverseHighLight: ColorSemanticToken { repositoryNeutralEmphasizedHigh }
    /// Has for value token repositoryOpacityWhiteLow (= "#EFF5FF1F")
    @objc open var surfaceInverseLowDark: ColorSemanticToken { repositoryOpacityWhiteLow }
    /// Has for value token repositoryNeutralEmphasizedHigh (= "#1F2632FF")
    @objc open var surfaceInverseLowLight: ColorSemanticToken { repositoryNeutralEmphasizedHigh }
    /// Has for value token repositoryOpacityWhiteLowest (= "#EFF5FF0A")
    @objc open var surfacePrimaryDark: ColorSemanticToken { repositoryOpacityWhiteLowest }
    /// Has for value token repositoryNeutralMutedWhite (= "#FFFFFFFF")
    @objc open var surfacePrimaryLight: ColorSemanticToken { repositoryNeutralMutedWhite }
    /// Has for value token repositoryOpacityWhiteLower (= "#EFF5FF14")
    @objc open var surfaceSecondaryDark: ColorSemanticToken { repositoryOpacityWhiteLower }
    /// Has for value token repositoryOpacityBlackLowest (= "#05052E0A")
    @objc open var surfaceSecondaryLight: ColorSemanticToken { repositoryOpacityBlackLowest }
    /// Has for value token repositoryAccentLow (= "#FA9EA6FF")
    @objc open var surfaceStatusAccentEmphasizedDark: ColorSemanticToken { repositoryAccentLow }
    /// Has for value token repositoryAccentMedium (= "#DB2345FF")
    @objc open var surfaceStatusAccentEmphasizedLight: ColorSemanticToken { repositoryAccentMedium }
    /// Has for value token repositoryOpacityAccentMedium (= "#8E1532AD")
    @objc open var surfaceStatusAccentMutedDark: ColorSemanticToken { repositoryOpacityAccentMedium }
    /// Has for value token repositoryOpacityAccentLow (= "#DB234514")
    @objc open var surfaceStatusAccentMutedLight: ColorSemanticToken { repositoryOpacityAccentLow }
    /// Has for value token repositoryInfoLow (= "#8AD5FFFF")
    @objc open var surfaceStatusInfoEmphasizedDark: ColorSemanticToken { repositoryInfoLow }
    /// Has for value token repositoryInfoHigh (= "#0073B2FF")
    @objc open var surfaceStatusInfoEmphasizedLight: ColorSemanticToken { repositoryInfoHigh }
    /// Has for value token repositoryOpacityInfoMedium (= "#00598A85")
    @objc open var surfaceStatusInfoMutedDark: ColorSemanticToken { repositoryOpacityInfoMedium }
    /// Has for value token repositoryOpacityInfoLow (= "#26B2FF14")
    @objc open var surfaceStatusInfoMutedLight: ColorSemanticToken { repositoryOpacityInfoLow }
    /// Has for value token repositoryNegativeLow (= "#FF8081FF")
    @objc open var surfaceStatusNegativeEmphasizedDark: ColorSemanticToken { repositoryNegativeLow }
    /// Has for value token repositoryNegativeMedium (= "#DB0002FF")
    @objc open var surfaceStatusNegativeEmphasizedLight: ColorSemanticToken { repositoryNegativeMedium }
    /// Has for value token repositoryOpacityNegativeMedium (= "#DB000252")
    @objc open var surfaceStatusNegativeMutedDark: ColorSemanticToken { repositoryOpacityNegativeMedium }
    /// Has for value token repositoryOpacityNegativeLow (= "#DB000214")
    @objc open var surfaceStatusNegativeMutedLight: ColorSemanticToken { repositoryOpacityNegativeLow }
    /// Has for value token repositoryPositiveLow (= "#94F0A4FF")
    @objc open var surfaceStatusPositiveEmphasizedDark: ColorSemanticToken { repositoryPositiveLow }
    /// Has for value token repositoryPositiveHigher (= "#138126FF")
    @objc open var surfaceStatusPositiveEmphasizedLight: ColorSemanticToken { repositoryPositiveHigher }
    /// Has for value token repositoryOpacityPositiveMedium (= "#0E621DA3")
    @objc open var surfaceStatusPositiveMutedDark: ColorSemanticToken { repositoryOpacityPositiveMedium }
    /// Has for value token repositoryOpacityPositiveLow (= "#3DE35A1F")
    @objc open var surfaceStatusPositiveMutedLight: ColorSemanticToken { repositoryOpacityPositiveLow }
    /// Has for value token repositoryWarningLow (= "#FFE270FF")
    @objc open var surfaceStatusWarningEmphasizedDark: ColorSemanticToken { repositoryWarningLow }
    /// Has for value token repositoryWarningMedium (= "#FFD000FF")
    @objc open var surfaceStatusWarningEmphasizedLight: ColorSemanticToken { repositoryWarningMedium }
    /// Has for value token repositoryOpacityWarningMedium (= "#6651007A")
    @objc open var surfaceStatusWarningMutedDark: ColorSemanticToken { repositoryOpacityWarningMedium }
    /// Has for value token repositoryOpacityWarningLow (= "#FFD00029")
    @objc open var surfaceStatusWarningMutedLight: ColorSemanticToken { repositoryOpacityWarningLow }
    /// Has for value token repositoryOpacityAccentMedium (= "#8E1532AD")
    @objc open var surfaceTertiaryDark: ColorSemanticToken { repositoryOpacityAccentMedium }
    /// Has for value token repositoryOpacityAccentLow (= "#DB234514")
    @objc open var surfaceTertiaryLight: ColorSemanticToken { repositoryOpacityAccentLow }
}
