// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeChipComponentTokensProvider: ChipComponentTokens {
    /// Has for value token colors.contentOnActionEnabled (= light: "#FFFFFFFF" / dark: "#08090DFF")
    @objc open var badgeColorBg: MultipleColorSemanticToken { colors.contentOnActionEnabled }
    /// Has for value token colors.contentDefault (= light: "#08090DFF" / dark: "#E9ECF1FF")
    @objc open var badgeColorContent: MultipleColorSemanticToken { colors.contentDefault }
    /// Has for value token borders.radiusLarge (= 12)
    @objc open var borderRadius: BorderRadiusSemanticToken { borders.radiusLarge }
    /// Has for value token borders.widthNone (= 0)
    @objc open var borderWidthSelected: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token borders.widthDefault (= 2)
    @objc open var borderWidthUnselected: BorderWidthSemanticToken { borders.widthDefault }
    /// Has for value token borders.widthMedium (= 3)
    @objc open var borderWidthUnselectedInteraction: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token colors.actionDisabled (= light: "#05052E33" / dark: "#EFF5FF33")
    @objc open var colorBgSelectedDisabled: MultipleColorSemanticToken { colors.actionDisabled }
    /// Has for value token colors.actionSelected (= light: "#2055E5FF" / dark: "#96C1FAFF")
    @objc open var colorBgSelectedEnabled: MultipleColorSemanticToken { colors.actionSelected }
    /// Has for value token colors.actionHover (= light: "#223CABFF" / dark: "#C1D8FCFF")
    @objc open var colorBgSelectedFocus: MultipleColorSemanticToken { colors.actionHover }
    /// Has for value token colors.actionHover (= light: "#223CABFF" / dark: "#C1D8FCFF")
    @objc open var colorBgSelectedHover: MultipleColorSemanticToken { colors.actionHover }
    /// Has for value token colors.actionPressed (= light: "#213787FF" / dark: "#DCE9FDFF")
    @objc open var colorBgSelectedPressed: MultipleColorSemanticToken { colors.actionPressed }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBgUnselectedDisabled: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBgUnselectedEnabled: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBgUnselectedFocus: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBgUnselectedHover: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBgUnselectedPressed: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBorderSelectedDisabled: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBorderSelectedEnabled: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBorderSelectedFocus: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBorderSelectedHover: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent (= light: "#05052E00" / dark: "#EFF5FF00")
    @objc open var colorBorderSelectedPressed: MultipleColorSemanticToken { colors.opacityTransparent }
    /// Has for value token colors.actionDisabled (= light: "#05052E33" / dark: "#EFF5FF33")
    @objc open var colorBorderUnselectedDisabled: MultipleColorSemanticToken { colors.actionDisabled }
    /// Has for value token colors.actionEnabled (= light: "#2055E5FF" / dark: "#96C1FAFF")
    @objc open var colorBorderUnselectedEnabled: MultipleColorSemanticToken { colors.actionEnabled }
    /// Has for value token colors.actionFocus (= light: "#223CABFF" / dark: "#C1D8FCFF")
    @objc open var colorBorderUnselectedFocus: MultipleColorSemanticToken { colors.actionFocus }
    /// Has for value token colors.actionHover (= light: "#223CABFF" / dark: "#C1D8FCFF")
    @objc open var colorBorderUnselectedHover: MultipleColorSemanticToken { colors.actionHover }
    /// Has for value token colors.actionPressed (= light: "#213787FF" / dark: "#DCE9FDFF")
    @objc open var colorBorderUnselectedPressed: MultipleColorSemanticToken { colors.actionPressed }
    /// Has for value token colors.contentOnActionDisabled (= light: "#FFFFFFFF" / dark: "#08090DFF")
    @objc open var colorContentSelectedDisabled: MultipleColorSemanticToken { colors.contentOnActionDisabled }
    /// Has for value token colors.contentOnActionEnabled (= light: "#FFFFFFFF" / dark: "#08090DFF")
    @objc open var colorContentSelectedEnabled: MultipleColorSemanticToken { colors.contentOnActionEnabled }
    /// Has for value token colors.contentOnActionFocus (= light: "#FFFFFFFF" / dark: "#08090DFF")
    @objc open var colorContentSelectedFocus: MultipleColorSemanticToken { colors.contentOnActionFocus }
    /// Has for value token colors.contentOnActionHover (= light: "#FFFFFFFF" / dark: "#08090DFF")
    @objc open var colorContentSelectedHover: MultipleColorSemanticToken { colors.contentOnActionHover }
    /// Has for value token colors.contentOnActionPressed (= light: "#FFFFFFFF" / dark: "#08090DFF")
    @objc open var colorContentSelectedPressed: MultipleColorSemanticToken { colors.contentOnActionPressed }
    /// Has for value token colors.contentOnActionSelected (= light: "#FFFFFFFF" / dark: "#08090DFF")
    @objc open var colorContentSelectedTickEnabled: MultipleColorSemanticToken { colors.contentOnActionSelected }
    /// Has for value token colors.actionDisabled (= light: "#05052E33" / dark: "#EFF5FF33")
    @objc open var colorContentUnselectedDisabled: MultipleColorSemanticToken { colors.actionDisabled }
    /// Has for value token colors.actionEnabled (= light: "#2055E5FF" / dark: "#96C1FAFF")
    @objc open var colorContentUnselectedEnabled: MultipleColorSemanticToken { colors.actionEnabled }
    /// Has for value token colors.actionFocus (= light: "#223CABFF" / dark: "#C1D8FCFF")
    @objc open var colorContentUnselectedFocus: MultipleColorSemanticToken { colors.actionFocus }
    /// Has for value token colors.actionHover (= light: "#223CABFF" / dark: "#C1D8FCFF")
    @objc open var colorContentUnselectedHover: MultipleColorSemanticToken { colors.actionHover }
    /// Has for value token colors.actionPressed (= light: "#213787FF" / dark: "#DCE9FDFF")
    @objc open var colorContentUnselectedPressed: MultipleColorSemanticToken { colors.actionPressed }
    /// Has for value token sizes.iconWithLabelMediumSizeSmall (= 16)
    @objc open var sizeIcon: SizeSemanticToken { sizes.iconWithLabelMediumSizeSmall }
    /// Has for value token dimensions._xsmall (= 32)
    @objc open var sizeMinHeight: SizeSemanticToken { dimensions._xsmall }
    /// Has for value token sizes.minInteractiveAreaDefault (= 48)
    @objc open var sizeMinHeightInteractiveArea: SizeSemanticToken { sizes.minInteractiveAreaDefault }
    /// Has for value token dimensions._2xlarge (= 52)
    @objc open var sizeMinWidth: SizeSemanticToken { dimensions._2xlarge }
    /// Has for value token spaces.columnGap2xsmall (= 4)
    @objc open var spaceColumnGapBadgeChevron: SpaceSemanticToken { spaces.columnGap2xsmall }
    /// Has for value token spaces.columnGapXsmall (= 6)
    @objc open var spaceColumnGapIcon: SpaceSemanticToken { spaces.columnGapXsmall }
    /// Has for value token spaces.paddingBlock2xsmall (= 6)
    @objc open var spacePaddingBlock: SpaceSemanticToken { spaces.paddingBlock2xsmall }
    /// Has for value token spaces.paddingBlockXsmall (= 8)
    @objc open var spacePaddingBlockIconOnly: SpaceSemanticToken { spaces.paddingBlockXsmall }
    /// Has for value token spaces.paddingInline4xsmall (= 2)
    @objc open var spacePaddingInlineBadgeStart: SpaceSemanticToken { spaces.paddingInline4xsmall }
    /// Has for value token spaces.paddingInlineXsmall (= 8)
    @objc open var spacePaddingInlineChevronEnd: SpaceSemanticToken { spaces.paddingInlineXsmall }
    /// Has for value token spaces.paddingInlineSmall (= 10)
    @objc open var spacePaddingInlineIcon: SpaceSemanticToken { spaces.paddingInlineSmall }
    /// Has for value token spaces.paddingInlineLarge (= 16)
    @objc open var spacePaddingInlineIconNone: SpaceSemanticToken { spaces.paddingInlineLarge }
}
