// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensRaw
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeTextInputComponentTokensProvider: TextInputComponentTokens {
    /// Has for value token borders.radiusDefault (= 6)
    @objc open var borderRadiusDefault: BorderRadiusSemanticToken { borders.radiusDefault }
    /// Has for value token borders.radiusDefault (= 6)
    @objc open var borderRadiusRounded: BorderRadiusSemanticToken { borders.radiusDefault }
    /// Has for value token borders.widthDefault (= 2)
    @objc open var borderWidthDefault: BorderWidthSemanticToken { borders.widthDefault }
    /// Has for value token borders.widthMedium (= 3)
    @objc open var borderWidthFocus: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token colors.borderDefault (= light: "#05052E33" / dark: "#EFF5FF33")
    @objc open var colorBorderEnabled: MultipleColorSemanticToken { colors.borderDefault }
    /// Has for value token colors.actionPressed (= light: "#213787FF" / dark: "#DCE9FDFF")
    @objc open var colorBorderFocus: MultipleColorSemanticToken { colors.actionPressed }
    /// Has for value token colors.actionHover (= light: "#223CABFF" / dark: "#C1D8FCFF")
    @objc open var colorBorderHover: MultipleColorSemanticToken { colors.actionHover }
    /// Has for value token colors.actionLoading (= light: "#213787FF" / dark: "#DCE9FDFF")
    @objc open var colorBorderLoading: MultipleColorSemanticToken { colors.actionLoading }
    /// Has for value token sizes.iconWithLabelLargeSizeXsmall (= 20)
    @objc open var sizeCountrySelectorFlagHeight: SizeSemanticToken { sizes.iconWithLabelLargeSizeXsmall }
    /// Has for value token DimensionRawTokens._600 (= 48)
    @objc open var sizeLabelMaxHeight: SizeSemanticToken { DimensionRawTokens._600 }
    /// Has for value token sizes.iconWithLabelLargeSizeSmall (= 24)
    @objc open var sizeLeadingIcon: SizeSemanticToken { sizes.iconWithLabelLargeSizeSmall }
    /// Has for value token DimensionRawTokens._4000 (= 480)
    @objc open var sizeMaxWidth: SizeSemanticToken { DimensionRawTokens._4000 }
    /// Has for value token DimensionRawTokens._750 (= 60)
    @objc open var sizeMinHeight: SizeSemanticToken { DimensionRawTokens._750 }
    /// Has for value token DimensionRawTokens._2500 (= 240)
    @objc open var sizeMinWidth: SizeSemanticToken { DimensionRawTokens._2500 }
    /// Has for value token dimensions._4xsmall (= 20)
    @objc open var sizeVerticalDividerHeight: SizeSemanticToken { dimensions._4xsmall }
    /// Has for value token spaces.columnGapMedium (= 12)
    @objc open var spaceColumnGapDefault: SpaceSemanticToken { spaces.columnGapMedium }
    /// Has for value token spaces.columnGapXsmall (= 6)
    @objc open var spaceColumnGapInlineText: SpaceSemanticToken { spaces.columnGapXsmall }
    /// Has for value token spaces.columnGap2xsmall (= 4)
    @objc open var spaceColumnGapLabelAsterisk: SpaceSemanticToken { spaces.columnGap2xsmall }
    /// Has for value token DimensionRawTokens.outOfSystem75 (= 3)
    @objc open var spaceColumnGapLabelSmallAsterisk: SpaceSemanticToken { DimensionRawTokens.outOfSystem75 }
    /// Has for value token spaces.columnGapXsmall (= 6)
    @objc open var spaceColumnGapTrailingErrorAction: SpaceSemanticToken { spaces.columnGapXsmall }
    /// Has for value token spaces.paddingBlock2xsmall (= 6)
    @objc open var spacePaddingBlockDefault: SpaceSemanticToken { spaces.paddingBlock2xsmall }
    /// Has for value token spaces.paddingBlockXsmall (= 8)
    @objc open var spacePaddingBlockTopHelperText: SpaceSemanticToken { spaces.paddingBlockXsmall }
    /// Has for value token spaces.paddingInlineXsmall (= 8)
    @objc open var spacePaddingInlineCountrySelectorEnd: SpaceSemanticToken { spaces.paddingInlineXsmall }
    /// Has for value token spaces.paddingInlineSmall (= 10)
    @objc open var spacePaddingInlineCountrySelectorStart: SpaceSemanticToken { spaces.paddingInlineSmall }
    /// Has for value token spaces.paddingInlineLarge (= 16)
    @objc open var spacePaddingInlineDefault: SpaceSemanticToken { spaces.paddingInlineLarge }
    /// Has for value token spaces.paddingInline2xsmall (= 6)
    @objc open var spacePaddingInlineTrailingAction: SpaceSemanticToken { spaces.paddingInline2xsmall }
    /// Has for value token spaces.rowGapNone (= 0)
    @objc open var spaceRowGapLabelInput: SpaceSemanticToken { spaces.rowGapNone }
}
