// Software: MISO iOS
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Pierre-Yves Lapersonne

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (BlueCoat brand)
// 🤖 Generated by Tokenator

extension BlueCoatThemeAlertMessageComponentTokensProvider: AlertMessageComponentTokens {
    /// Has for value token borders.widthThin (= 1)
    @objc open var borderWidth: BorderWidthSemanticToken { borders.widthThin }
    /// Has for value token spaces.rowGapNone (= 0)
    @objc open var spaceRowGapBullet: SpaceSemanticToken { spaces.rowGapNone }
}
