// Software: MISO iOS (fork of OUDS iOS)
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for divider components like `MISOHorizontalDivider` and `MISOVerticalDivider`
/// Use for tokens providers like `BlueCoatThemeDividerComponentTokensProvider`.
///
/// - Since: OUDS 0.13.0
public protocol DividerComponentTokens {

    var borderWidth: BorderWidthSemanticToken { get }
}

// swiftlint:enable missing_docs
