// Software: MISO iOS (fork of OUDS iOS)
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for input components like `MISOProgressIndicator`
/// Use for tokens providers like `BlueCoatThemeProgressIndicatorComponentTokensProvider`.
///
/// - Since: OUDS 3.0.0
public protocol ProgressIndicatorComponentTokens {

    // MARK: - Colors

    var colorContentTrack: MultipleColorSemanticToken { get }

    // MARK: - Borders

    var borderRadiusDefault: BorderRadiusSemanticToken { get }
    var borderRadiusRounded: BorderRadiusSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingBlock: SpaceSemanticToken { get }
    var spaceColumnGap: SpaceSemanticToken { get }

    // MARK: - Sizes

    var sizeLinearIndicatorHeight: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
