// Software: MISO iOS (fork of OUDS iOS)
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for skeleton components like `MISOSkeleton`
/// Use for tokens providers like `BlueCoatThemeSkeletonComponentTokensProvider`.
///
/// - Since: OUDS 0.10.0
public protocol SkeletonComponentTokens {

    // MARK: - Color

    var colorBg: MultipleColorSemanticToken { get }
    var colorGradientMiddle: MultipleColorSemanticToken { get }
    var colorGradientStartEnd: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
