// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensRaw
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeEffectSemanticTokensProvider: EffectSemanticTokens {
    /// Has for value token EffectRawTokens.blur80 (= 8)
    @objc open var blurBackdrop: EffectSemanticToken { EffectRawTokens.blur80 }
    /// Has for value token EffectRawTokens.blur480 (= 48)
    @objc open var blurDrag: EffectSemanticToken { EffectRawTokens.blur480 }
}
