// Software: MISO iOS (fork of OUDS iOS)
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **elevations** but multiple so as to pack light and dark variants
/// It wraps elevation colors as tokens.
///
/// - Since: OUDS 0.20.0
public protocol ElevationMultipleSemanticTokens {

    // MARK: Semantic token - Elevation - Color

    var colorElevated: ElevationMultipleColorSemanticToken { get }
    var colorRaised: ElevationMultipleColorSemanticToken { get }
    var colorDrag: ElevationMultipleColorSemanticToken { get }
    var colorEmphasized: ElevationMultipleColorSemanticToken { get }
    var colorSticky: ElevationMultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
